CREATE TABLE TBR.IDENTITIES
    (IDENTITY_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY CONSTRAINT IDENTITY_PK PRIMARY KEY, 
    IDENTITY_DISPLAYNAME VARCHAR(255),
    IDENTITY_EMAIL VARCHAR(255),
    IDENTITY_BIRTHDATE DATE,
    UNIQUE (IDENTITY_EMAIL)
    );
    
    create table ADMIN
(
ADMIN_USER varchar(255)primary key,
ADMIN_PASS varchar(255)
);

INSERT INTO ADMIN(ADMIN_USER, ADMIN_PASS) VALUES('root','admin123');
INSERT INTO ADMIN(ADMIN_USER, ADMIN_PASS) VALUES('mathew','admin123');

